version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: hospital-db
    environment:
      POSTGRES_DB: hospital_db
      POSTGRES_USER: hospital_user
      POSTGRES_PASSWORD: hospital_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hospital_user -d hospital_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app-node1:
    build: .
    image: hospital-cluster:latest
    container_name: hospital-app-1
    ports:
      - "8081:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/hospital_db
      DB_USER: hospital_user
      DB_PASSWORD: hospital_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      NODE_ID: 1
      CLUSTER_PEERS: app-node1,app-node2,app-node3,app-node4
    depends_on:
      db:
        condition: service_healthy

  app-node2:
    image: hospital-cluster:latest
    container_name: hospital-app-2
    ports:
      - "8082:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/hospital_db
      DB_USER: hospital_user
      DB_PASSWORD: hospital_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      NODE_ID: 2
      CLUSTER_PEERS: app-node1,app-node2,app-node3,app-node4
    depends_on:
      db:
        condition: service_healthy

  app-node3:
    image: hospital-cluster:latest
    container_name: hospital-app-3
    ports:
      - "8083:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/hospital_db
      DB_USER: hospital_user
      DB_PASSWORD: hospital_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      NODE_ID: 3
      CLUSTER_PEERS: app-node1,app-node2,app-node3,app-node4
    depends_on:
      db:
        condition: service_healthy

  app-node4:
    image: hospital-cluster:latest
    container_name: hospital-app-4
    ports:
      - "8084:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/hospital_db
      DB_USER: hospital_user
      DB_PASSWORD: hospital_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      NODE_ID: 4
      CLUSTER_PEERS: app-node1,app-node2,app-node3,app-node4
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
