version: '3.8'
services:
  hospital:
    image: 192.168.101.3:5000/hospital:latest
    ports:
      - mode: host
        target: 8080
        published: 8080
        protocol: tcp
    environment:
      - DB_URL=jdbc:postgresql://db:5432/hospital_db
      - DB_USER=hospital_user
      - DB_PASSWORD=hospital_pass
    deploy:
      mode: global
    networks:
      - hospital-net
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=hospital_db
      - POSTGRES_USER=hospital_user
      - POSTGRES_PASSWORD=hospital_pass
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - hospital-net
networks:
  hospital-net:
    driver: overlay
    attachable: true